version: "3.9"

services:
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  web:
    build:
      # Use the project root as context; our Dockerfile lives in devops/
      context: ..
      dockerfile: devops/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      
volumes:
  redis_data:
