version: "3.9"

services:
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  web:
    build:
      context: ..
      dockerfile: devops/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../.env.prod
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-${API_NAME:-api}_db}
      
volumes:
  redis_data:
