FROM python:3.11-slim-bookworm

WORKDIR /app

COPY requirements.dev.txt .
RUN pip install --no-cache-dir -r requirements.dev.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
