FROM python:3.11-slim-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y netcat-traditional && rm -rf /var/lib/apt/lists/*

COPY requirements.prod.txt .
COPY requirements.dev.txt .
RUN pip install --no-cache-dir -r requirements.dev.txt

COPY . .

# Fix permissions and line endings more aggressively
RUN find /app/scripts -type f -name "*.sh" -exec chmod +x {} \; && \
    find /app/scripts -type f -name "*.sh" -exec sed -i -e 's/\r$//' {} \; && \
    find /app/scripts -type f -name "*.sh" -exec sh -c 'echo "#!/bin/bash" > /tmp/tempfile && cat {} >> /tmp/tempfile && mv /tmp/tempfile {}' \;

ENV PYTHONPATH=/app
ENV ENVIRONMENT=dev

CMD ["/bin/bash", "./scripts/init_dev.sh"]
