FROM python:3.11-slim-bookworm

WORKDIR /app

ENV ENVIRONMENT=test

COPY requirements.prod.txt .
COPY requirements.dev.txt .
COPY requirements.test.txt .
RUN pip install --no-cache-dir -r requirements.test.txt

COPY . .

CMD ["pytest", "--cov=src", "--cov-report=term-missing"]
