"""initial

Revision ID: 62af5c82d8c9
Revises:
Create Date: 2025-02-10 21:37:37.976089

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "62af5c82d8c9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "example",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_example_id"), "example", ["id"], unique=False)
    op.create_index(op.f("ix_example_name"), "example", ["name"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_example_name"), table_name="example")
    op.drop_index(op.f("ix_example_id"), table_name="example")
    op.drop_table("example")
    # ### end Alembic commands ###
